### ISSUE TITLE
v2.1.1.1 深色模式部分位置字体颜色不对

### ISSUE THREAD

**Issue by RainPPR** [TLEWA/O2-luogu#54]
1. 未登录时：包括专栏、主页、<https://www.luogu.com.cn/problem/list> 版本的 UI 因为有框所以没问题
![image](https://github.com/user-attachments/assets/097a42cc-1bdc-40b3-9e42-36e01151dbac)
![image](https://github.com/user-attachments/assets/fa947b6d-25e4-4f73-ad35-300f525b189b)
![image](https://github.com/user-attachments/assets/4616dd23-576d-47fe-a4cf-3ec1b77b8ada)

**Comment by RainPPR** [comment]
补充：浅色模式，实验性代码块字体渲染，
![image](https://github.com/user-attachments/assets/e6d7f4cd-043c-4a30-a37a-650886584ea0)
效果不好，颜色太浅了

**Comment by TLEWA** [comment]
感谢反馈

**Comment by TLEWA** [comment]
fixed
