### ISSUE TITLE
完善卡片圆角

### ISSUE THREAD

**Issue by 2043356647** [TLEWA/O2-luogu#67]
圆角设置对个人主页的卡片没有效果（所以有“圆角”的设置都试了）

**Comment by 2043356647** [comment]
卡片的圆角设置在首页可以正常显示，但在个人主页不行
![FireShot Capture 001 - Stylus - clngdbkpkpeebahjckkjfobafhncgmne (1)](https://github.com/user-attachments/assets/3bc56377-8ff7-41e7-94d9-63c3b0638136)
![FireShot Capture 002 - Stylus - clngdbkpkpeebahjckkjfobafhncgmne (1)](https://github.com/user-attachments/assets/c02c4f4c-c45f-4a20-92f0-c23f1d742abc)
![FireShot Capture 004 - 首页 - 洛谷 - 计算机科学教育新生态 - www luogu com cn (1)](https://github.com/user-attachments/assets/99b63495-8aac-4cda-aec0-9c6d796c22a2)
![FireShot Capture 003 - Y204335 的个人中心 - 洛谷 - 计算机科学教育新生态 - www luogu com cn (1)](https://github.com/user-attachments/assets/ab78a0c7-bebe-469d-93d4-deb806e003bf)

**Comment by TLEWA** [comment]
以 2.2.0.0 pre1 的表现为准
